export interface TRIFacility {
  id: string;
  name: string;
  city: string;
  state: string;
  fips: string;
  coordinates: [number, number]; // [longitude, latitude]
  emissionsLbs: number;
  primaryChemicals: string[];
  sector: string;
  hazardLevel: "Critical" | "High" | "Moderate";
  address?: string;
}

export const TRI_FACILITIES: TRIFacility[] = [
  {
    id: "TRI-001",
    name: "ExxonMobil Baytown Complex",
    city: "Baytown",
    state: "TX",
    fips: "48201",
    coordinates: [-95.0118, 29.7355],
    emissionsLbs: 4850000,
    primaryChemicals: ["Benzene", "1,3-Butadiene", "Toluene", "Ethylene", "Ammonia"],
    sector: "Petrochemical & Refining",
    hazardLevel: "Critical",
    address: "5000 Bayway Dr, Baytown, TX 77520",
  },
  {
    id: "TRI-002",
    name: "Shell Norco Manufacturing Complex",
    city: "Norco",
    state: "LA",
    fips: "22089",
    coordinates: [-90.4124, 29.9986],
    emissionsLbs: 3920000,
    primaryChemicals: ["Benzene", "Xylene", "Toluene", "1,3-Butadiene"],
    sector: "Petrochemical & Refining",
    hazardLevel: "Critical",
    address: "15536 River Rd, Norco, LA 70079",
  },
  {
    id: "TRI-003",
    name: "Formosa Plastics Corp",
    city: "Point Comfort",
    state: "TX",
    fips: "48057",
    coordinates: [-96.5597, 28.6756],
    emissionsLbs: 5410000,
    primaryChemicals: ["Vinyl Chloride", "Ethylene Dichloride", "Chlorine", "Ethylene Oxide"],
    sector: "Plastics & Resins",
    hazardLevel: "Critical",
    address: "201 Formosa Dr, Point Comfort, TX 77978",
  },
  {
    id: "TRI-004",
    name: "Gary Works - US Steel",
    city: "Gary",
    state: "IN",
    fips: "18089",
    coordinates: [-87.3372, 41.6111],
    emissionsLbs: 7200000,
    primaryChemicals: ["Lead Compounds", "Manganese Compounds", "Zinc Compounds", "Chromium"],
    sector: "Primary Metal Manufacturing",
    hazardLevel: "Critical",
    address: "1 N Broadway, Gary, IN 46402",
  },
  {
    id: "TRI-005",
    name: "Dow Chemical Freeport Complex",
    city: "Freeport",
    state: "TX",
    fips: "48039",
    coordinates: [-95.3582, 28.9542],
    emissionsLbs: 6150000,
    primaryChemicals: ["Ethylene Oxide", "Chlorine", "Vinyl Chloride", "Dioxin"],
    sector: "Chemical Manufacturing",
    hazardLevel: "Critical",
    address: "2301 N Brazosport Blvd, Freeport, TX 77541",
  },
  {
    id: "TRI-006",
    name: "BP Whiting Refinery",
    city: "Whiting",
    state: "IN",
    fips: "18089",
    coordinates: [-87.4912, 41.6811],
    emissionsLbs: 3450000,
    primaryChemicals: ["Benzene", "Sulfuric Acid", "Toluene", "Xylene"],
    sector: "Petroleum Refining",
    hazardLevel: "High",
    address: "2815 Indianapolis Blvd, Whiting, IN 46394",
  },
  {
    id: "TRI-007",
    name: "BASF Geismar Complex",
    city: "Geismar",
    state: "LA",
    fips: "22005",
    coordinates: [-91.0112, 30.2241],
    emissionsLbs: 4100000,
    primaryChemicals: ["Ammonia", "Formaldehyde", "MDI / Isocyanates", "Methanol"],
    sector: "Chemical Manufacturing",
    hazardLevel: "Critical",
    address: "8404 River Rd, Geismar, LA 70734",
  },
  {
    id: "TRI-008",
    name: "Chevron Pascagoula Refinery",
    city: "Pascagoula",
    state: "MS",
    fips: "28059",
    coordinates: [-88.5034, 30.3477],
    emissionsLbs: 3680000,
    primaryChemicals: ["Xylene", "Benzene", "Hydrogen Cyanide", "Nickel Compounds"],
    sector: "Petroleum Refining",
    hazardLevel: "High",
    address: "2501 Pascagoula Rd, Pascagoula, MS 39568",
  },
  {
    id: "TRI-009",
    name: "Eastman Chemical Kingsport Site",
    city: "Kingsport",
    state: "TN",
    fips: "47163",
    coordinates: [-82.5515, 36.5298],
    emissionsLbs: 5890000,
    primaryChemicals: ["Methanol", "Acetic Acid", "Acetone", "Formaldehyde"],
    sector: "Chemical Manufacturing",
    hazardLevel: "Critical",
    address: "200 S Wilcox Dr, Kingsport, TN 37660",
  },
  {
    id: "TRI-010",
    name: "CF Industries Donaldsonville Complex",
    city: "Donaldsonville",
    state: "LA",
    fips: "22005",
    coordinates: [-90.9632, 30.0894],
    emissionsLbs: 8420000,
    primaryChemicals: ["Ammonia", "Nitric Acid", "Ammonium Nitrate", "Urea"],
    sector: "Fertilizer Manufacturing",
    hazardLevel: "Critical",
    address: "39018 LA-308, Donaldsonville, LA 70346",
  },
  {
    id: "TRI-011",
    name: "Clairton Coke Works - US Steel",
    city: "Clairton",
    state: "PA",
    fips: "42003",
    coordinates: [-79.8828, 40.2981],
    emissionsLbs: 4920000,
    primaryChemicals: ["Benzene", "Hydrogen Cyanide", "Ammonia", "Phenol"],
    sector: "Steel & Coke Production",
    hazardLevel: "Critical",
    address: "400 State St, Clairton, PA 15025",
  },
  {
    id: "TRI-012",
    name: "Marathon Detroit Refinery",
    city: "Detroit",
    state: "MI",
    fips: "26163",
    coordinates: [-83.1554, 42.2882],
    emissionsLbs: 2890000,
    primaryChemicals: ["Benzene", "Hydrogen Sulfide", "Toluene", "Nickel Compounds"],
    sector: "Petroleum Refining",
    hazardLevel: "High",
    address: "1300 S Fort St, Detroit, MI 48217",
  },
  {
    id: "TRI-013",
    name: "Ascend Performance Materials",
    city: "Cantonment",
    state: "FL",
    fips: "12033",
    coordinates: [-87.3182, 30.6092],
    emissionsLbs: 3120000,
    primaryChemicals: ["Ammonia", "Cyclohexane", "Acetonitrile", "Adiponitrile"],
    sector: "Synthetic Fibers & Resins",
    hazardLevel: "High",
    address: "3000 Old Chemstrand Rd, Cantonment, FL 32533",
  },
  {
    id: "TRI-014",
    name: "Freeport-McMoRan Morenci Mine",
    city: "Morenci",
    state: "AZ",
    fips: "04011",
    coordinates: [-109.3326, 33.0807],
    emissionsLbs: 12500000,
    primaryChemicals: ["Copper Compounds", "Lead Compounds", "Sulfuric Acid", "Arsenic"],
    sector: "Metal Mining",
    hazardLevel: "Critical",
    address: "US-191, Morenci, AZ 85540",
  },
  {
    id: "TRI-015",
    name: "Kennecott Bingham Canyon Mine",
    city: "Magna",
    state: "UT",
    fips: "49035",
    coordinates: [-112.1481, 40.5233],
    emissionsLbs: 9800000,
    primaryChemicals: ["Lead Compounds", "Arsenic", "Copper Compounds", "Mercury"],
    sector: "Metal Mining",
    hazardLevel: "Critical",
    address: "8362 W 10200 S, Bingham Canyon, UT 84006",
  },
  {
    id: "TRI-016",
    name: "Westlake Petrochemical Lake Charles",
    city: "Westlake",
    state: "LA",
    fips: "22019",
    coordinates: [-93.2641, 30.2289],
    emissionsLbs: 4600000,
    primaryChemicals: ["Vinyl Chloride", "Ethylene Dichloride", "Chlorine"],
    sector: "Petrochemicals",
    hazardLevel: "Critical",
    address: "900 Highway 108, Westlake, LA 70669",
  },
  {
    id: "TRI-017",
    name: "Valero Corpus Christi Refinery",
    city: "Corpus Christi",
    state: "TX",
    fips: "48215",
    coordinates: [-97.4384, 27.8184],
    emissionsLbs: 3250000,
    primaryChemicals: ["Benzene", "Toluene", "Sulfuric Acid", "Hydrogen Fluoride"],
    sector: "Petroleum Refining",
    hazardLevel: "High",
    address: "1300 Corn Products Rd, Corpus Christi, TX 78409",
  },
  {
    id: "TRI-018",
    name: "Sabic Innovative Plastics",
    city: "Mount Vernon",
    state: "IN",
    fips: "18129",
    coordinates: [-87.8931, 37.9348],
    emissionsLbs: 2750000,
    primaryChemicals: ["Phenol", "Bisphenol A", "Phosgene", "Dichloromethane"],
    sector: "Plastics & Resins",
    hazardLevel: "High",
    address: "1 Lexan Ln, Mount Vernon, IN 47620",
  },
  {
    id: "TRI-019",
    name: "Chevron Richmond Refinery",
    city: "Richmond",
    state: "CA",
    fips: "06013",
    coordinates: [-122.3892, 37.9515],
    emissionsLbs: 2100000,
    primaryChemicals: ["Benzene", "Sulfuric Acid", "Ammonia", "Xylene"],
    sector: "Petroleum Refining",
    hazardLevel: "High",
    address: "841 Castro St, Richmond, CA 94801",
  },
  {
    id: "TRI-020",
    name: "Covestro Baytown Industrial Park",
    city: "Baytown",
    state: "TX",
    fips: "48201",
    coordinates: [-94.9584, 29.7612],
    emissionsLbs: 3400000,
    primaryChemicals: ["Toluene Diisocyanate", "Chlorine", "Phosgene", "Aniline"],
    sector: "Polymer Chemicals",
    hazardLevel: "High",
    address: "8500 W Bay Rd, Baytown, TX 77523",
  },
  {
    id: "TRI-021",
    name: "Shell Deer Park Chemical Complex",
    city: "Deer Park",
    state: "TX",
    fips: "48201",
    coordinates: [-95.1274, 29.7092],
    emissionsLbs: 3880000,
    primaryChemicals: ["Benzene", "1,3-Butadiene", "Ethylene Oxide", "Phenol"],
    sector: "Chemical Manufacturing",
    hazardLevel: "Critical",
    address: "5900 Highway 225, Deer Park, TX 77536",
  },
  {
    id: "TRI-022",
    name: "Chemours Chambers Works",
    city: "Deepwater",
    state: "NJ",
    fips: "34033",
    coordinates: [-75.4982, 39.6892],
    emissionsLbs: 2640000,
    primaryChemicals: ["PFAS / Fluorinated Compounds", "Ammonia", "Aniline", "Chlorine"],
    sector: "Specialty Chemicals",
    hazardLevel: "High",
    address: "67 Route 130, Deepwater, NJ 08023",
  },
  {
    id: "TRI-023",
    name: "Sasol Chemicals Lake Charles",
    city: "Westlake",
    state: "LA",
    fips: "22019",
    coordinates: [-93.2844, 30.2415],
    emissionsLbs: 5300000,
    primaryChemicals: ["Ethylene Oxide", "Triethylaluminum", "Linear Alcohols"],
    sector: "Petrochemicals",
    hazardLevel: "Critical",
    address: "2201 Old Spanish Trail, Westlake, LA 70669",
  },
  {
    id: "TRI-024",
    name: "Marathon Canton Refinery",
    city: "Canton",
    state: "OH",
    fips: "39151",
    coordinates: [-81.3644, 40.7712],
    emissionsLbs: 1820000,
    primaryChemicals: ["Benzene", "Toluene", "Xylene", "Hydrogen Sulfide"],
    sector: "Petroleum Refining",
    hazardLevel: "Moderate",
    address: "2408 Gambrinus Ave SW, Canton, OH 44706",
  },
  {
    id: "TRI-025",
    name: "BP Cooper River Plant",
    city: "Wando",
    state: "SC",
    fips: "45015",
    coordinates: [-79.8812, 32.9615],
    emissionsLbs: 1650000,
    primaryChemicals: ["Terephthalic Acid", "Xylene", "Methanol"],
    sector: "Chemical Manufacturing",
    hazardLevel: "Moderate",
    address: "4700 Highway 41, Wando, SC 29492",
  },
  {
    id: "TRI-026",
    name: "WestRock Covington Mill",
    city: "Covington",
    state: "VA",
    fips: "51005",
    coordinates: [-79.9881, 37.7812],
    emissionsLbs: 2420000,
    primaryChemicals: ["Methanol", "Ammonia", "Sulfuric Acid", "Acetaldehyde"],
    sector: "Paper & Packaging",
    hazardLevel: "Moderate",
    address: "104 E Riverside St, Covington, VA 24426",
  },
  {
    id: "TRI-027",
    name: "Suncor Commerce City Refinery",
    city: "Commerce City",
    state: "CO",
    fips: "08001",
    coordinates: [-104.9512, 39.8142],
    emissionsLbs: 1790000,
    primaryChemicals: ["Benzene", "Hydrogen Cyanide", "Hydrogen Fluoride", "Toluene"],
    sector: "Petroleum Refining",
    hazardLevel: "High",
    address: "5801 Brighton Blvd, Commerce City, CO 80022",
  },
  {
    id: "TRI-028",
    name: "Archer Daniels Midland Decatur",
    city: "Decatur",
    state: "IL",
    fips: "17115",
    coordinates: [-88.9042, 39.8512],
    emissionsLbs: 3820000,
    primaryChemicals: ["n-Hexane", "Methanol", "Sulfuric Acid", "Ammonia"],
    sector: "Agribusiness & Processing",
    hazardLevel: "High",
    address: "4666 Faries Pkwy, Decatur, IL 62526",
  },
  {
    id: "TRI-029",
    name: "Joliet Chemical Complex - Ineos",
    city: "Channahon",
    state: "IL",
    fips: "17197",
    coordinates: [-88.2251, 41.4281],
    emissionsLbs: 2150000,
    primaryChemicals: ["Maleic Anhydride", "Xylene", "Phthalic Anhydride"],
    sector: "Chemical Manufacturing",
    hazardLevel: "Moderate",
    address: "23425 W Eames St, Channahon, IL 60410",
  },
  {
    id: "TRI-030",
    name: "Phillips 66 Ferndale Refinery",
    city: "Ferndale",
    state: "WA",
    fips: "53073",
    coordinates: [-122.7092, 48.8241],
    emissionsLbs: 1450000,
    primaryChemicals: ["Benzene", "Toluene", "Xylene", "Ammonia"],
    sector: "Petroleum Refining",
    hazardLevel: "Moderate",
    address: "3901 Unick Rd, Ferndale, WA 98248",
  }
];

export function getTriFacilities(): TRIFacility[] {
  return TRI_FACILITIES;
}

export function getTriFacilitiesByFips(fips: string): TRIFacility[] {
  return TRI_FACILITIES.filter((f) => f.fips === fips);
}

export function getCountyTriSummary(fips: string) {
  const facilities = getTriFacilitiesByFips(fips);
  const totalEmissions = facilities.reduce((acc, f) => acc + f.emissionsLbs, 0);
  const chemicals = Array.from(new Set(facilities.flatMap((f) => f.primaryChemicals)));
  return {
    facilityCount: facilities.length,
    totalEmissionsLbs: totalEmissions,
    facilities,
    topChemicals: chemicals.slice(0, 5),
  };
}
